# app/app_pending.py
import os
import requests
import streamlit as st

# ----- ENV -----
APPS_SCRIPT_URL   = os.environ.get("APPS_SCRIPT_URL", "")
APPS_SCRIPT_TOKEN = os.environ.get("APPS_SCRIPT_TOKEN", "")
WALLET_TRON       = os.environ.get("WALLET_TRON", "TRON_ADDRESS_HERE")  # set in Render

# ----- PAGE CONFIG -----
st.set_page_config(page_title="Buy PRO • Market Sentiment", layout="centered")

# ----- HEADER -----
st.title("Market Sentiment PRO — Buy / Create Pending Order")
st.write(
    "Enter your email, select a plan, and paste the **Tax ID** generated by your payment gateway. "
    "After creating a pending order, send the payment and **include the same Tax ID in the TRON memo**."
)

# ----- FORM INPUTS -----
email = st.text_input("Email", placeholder="client@example.com")
plan  = st.selectbox("Plan", ["Monthly (15 USDT)", "Quarterly (40 USDT)"])
plan_name = "Monthly" if plan.startswith("Monthly") else "Quarterly"
amount = 15.0 if plan_name == "Monthly" else 40.0

tax_id = st.text_input("Tax ID (from your payment gateway)", placeholder="Paste the exact Tax ID provided by the gateway")
note   = st.text_input("Note (optional)", value="linkedin-campaign")

# ----- PAYMENT DETAILS -----
st.subheader("Payment Details (USDT • TRC20)")
st.code(
    f"Address: {WALLET_TRON}\n"
    f"Network: TRON (TRC20)\n"
    f"Amount:  {amount:.2f} USDT\n"
    f"Memo:    <your Tax ID>",
    language="bash"
)
st.caption("Important: The TRON memo must contain the exact Tax ID you entered above.")

# quick summary tiles
c1, c2 = st.columns(2)
with c1:
    st.metric("Selected Plan", plan_name)
with c2:
    st.metric("Amount (USDT-TRC20)", f"{amount:.2f}")

st.divider()

# ----- CREATE PENDING ORDER -----
submit = st.button("Create Pending Order")

if submit:
    # basic validations
    if not (APPS_SCRIPT_URL and APPS_SCRIPT_TOKEN):
        st.error("Server configuration is missing. Please set APPS_SCRIPT_URL and APPS_SCRIPT_TOKEN in environment.")
    elif not email:
        st.error("Email is required.")
    elif not tax_id:
        st.error("Tax ID is required (provided by your payment gateway).")
    else:
        payload = {
            "token": APPS_SCRIPT_TOKEN,
            "action": "add_pending",
            "tax_id": tax_id,
            "email": email,
            "plan": plan_name,
            "amount": f"{amount:.2f}",
            "note": note
        }
        try:
            r = requests.post(APPS_SCRIPT_URL, json=payload, timeout=20)
            r.raise_for_status()
            j = r.json()
            if j.get("ok"):
                st.success(
                    "✅ Pending order created successfully.\n\n"
                    "Now send the payment to the TRON address above and **include the SAME Tax ID in the memo**.\n"
                    "Your license will be issued automatically after the transaction is detected on-chain."
                )
            else:
                st.error(f"Apps Script responded with an error: {j}")
        except Exception as e:
            st.error(f"Failed to create pending order: {e}")

# ----- HELP / FAQ -----
with st.expander("What is the Tax ID?"):
    st.write(
        "It is a unique code generated by your **payment gateway**. "
        "You must enter it here and also include it in the TRON memo when sending the payment."
    )

with st.expander("When will my license be issued?"):
    st.write(
        "Our watcher checks TRON USDT-TRC20 transactions periodically. "
        "Once your payment with the correct memo (Tax ID) and amount is detected, "
        "your license is issued automatically and sent to your email."
    )
