name: LinkedIn Daily Post

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch: {}

jobs:
  post-linkedin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build message & send to Zapier
        env:
          ZAPIER_HOOK_URL: ${{ secrets.ZAPIER_HOOK_URL }}
        run: |
          python post_summary.py || true
