name: LinkedIn Daily Post

on:
  workflow_dispatch: {}
  schedule:
    - cron: "25 6 * * *"   # هر روز 06:25 UTC

jobs:
  post-linkedin:
    runs-on: ubuntu-latest
    env:
      DATA_URL: ${{ vars.DATA_URL }}
      ZAPIER_HOOK_URL: ${{ secrets.ZAPIER_HOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: python -m pip install --upgrade pip

      - name: Build message & send to Zapier
        run: |
          python post_summary.py || true
