name: LinkedIn Daily Post

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  post-linkedin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build sentiment text
        run: |
          python post_summary.py || true

      - name: Send to Zapier (curl)
        env:
          ZAPIER_HOOK_URL: ${{ secrets.ZAPIER_HOOK_URL }}
        run: |
          test -n "$ZAPIER_HOOK_URL" || (echo "ZAPIER_HOOK_URL missing" && exit 1)
          echo "[SEND] POST → $ZAPIER_HOOK_URL"
          http_code=$(curl -sS -o resp.txt -w "%{http_code}" \
            -X POST "$ZAPIER_HOOK_URL" \
            -H "Content-Type: application/json" \
            --data "{\"text\": \"$(cat summary.txt | sed 's/\"/\\"/g')\"}")
          echo "HTTP code: $http_code"
          echo "--- Response ---"
          cat resp.txt
          echo "----------------"
          [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]
